#!/usr/bin/env php
<?php

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require('/var/www/html/helpers/DockerEnv.php');
\DockerEnv::init();
$config = \DockerEnv::consoleConfig();

$application = new yii\console\Application($config);
\Yii::setAlias('common', __DIR__ . '/packages/someet-common/');
\Yii::setAlias('user', __DIR__ . '/packages/yii2-user/');
$exitCode = $application->run();
exit($exitCode);
